export const colors = [
  // 'red',
  // 'darkred',
  'lightred',
  // 'yellow',
  // 'darkyellow',
  'lightyellow',
  // 'blue',
  // 'darkblue',
  'lightblue',
  // 'green',
  // 'darkgreen',
  'lightgreen',
  'cyan',
  // 'darkcyan',
  'lightcyan',
  // 'purple',
  // 'darkpurple',
  'lightpurple',
];
